name: CI

# Controls when the workflow will run
on:

  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build project
        run: |
          cd firmware
          make clean
          make build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Make test library
        run: |
          cd firmware/tests/cpputest
          ./autogen.sh
          ./configure
          make
          cd ../../..
      - name: Run unit tests
        run: |
          cd firmware
          make clean
          make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
      - run: pip install cpplint
      - run: cpplint --filter=-legal/copyright,-build/include_subdir,-runtime/printf,-whitespace/braces,-whitespace/newline, --recursive firmware/src, --linelength=130
      - run: cpplint --filter=-legal/copyright,-build/include_subdir,-runtime/printf,-whitespace/braces,-whitespace/newline, --recursive firmware/inc, --linelength=130
